export const ValidationLimits = {
  TASK_DETAILS_MAX_LENGTH: 2000,
  TASK_DETAILS_MIN_LENGTH: 1,
  TAG_MAX_LENGTH: 50,
  TAG_MIN_LENGTH: 1,
  MAX_TAGS: 20,
  MAX_DEPENDENCIES: 50,
  TASK_ID_MAX_LENGTH: 100,
} as const;
